version: "3.7"

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:7.0.7
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
